### ISSUE TITLE
muita demanda

### ISSUE THREAD

**Issue by lucasfariaslf** [guilbran/hello-world#2]
tentei dar fork, mas puts, muita demanda... Como resolvo? @GreedBlink, azeita aí, pfv.

**Comment by guilbran** [comment]
@GreedBlink preciso da sua ajuda aqui. Tem muita demanda

**Comment by GreedBlink** [comment]
@guilbran pq tu tá querendo dar fork no seu próprio repositório?

**Comment by lucasfariaslf** [comment]
mobral, sou eu que to querendo...

tanta demanda te bugou

**Comment by GreedBlink** [comment]
Mobral, pq tu criou esse issues? Com tanta demanda, tu ainda consegue abrir issues no repositório desse mestre! Tu é o bichão mermo em! Hahaha
